#ifndef POKEEMEREX_EMU_ACCURACY_TESTS_H
#define POKEEMEREX_EMU_ACCURACY_TESTS_H

enum {
    TEST_EXPECT_8 = 0,
    TEST_EXPECT_16,
    TEST_EXPECT_32
};

void RunEmulationAccuracyTests(void);

#endif //POKEEMEREX_EMU_ACCURACY_TESTS_H
